name: instagram_basic_display
description: An incomplete dart library for interfacing with the Instagram Basic Display API.
version: 0.0.1
author: Will Roxby<will.roxby@booza.app>
homepage: https://github.com/willroxby/instagram_basic_display.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  json_annotation: ^3.1.1
  oauth2: ^1.6.3
#dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec