name: instagram_basic_display
description: An incomplete dart library for interfacing with the Instagram Basic Display API.
version: 0.0.1
author: Will Roxby<will.roxby@booza.app>
homepage: https://github.com/willroxby/instagram_basic_display.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.0
  json_annotation: ^4.0.0
  oauth2: ^2.0.0
  pedantic: ^1.11.0

dev_dependencies:
#  test: ^1.15.7
  build_runner: ^1.11.5
  json_serializable: ^4.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec